import { useState, useCallback } from "react";
import { Message, Conversation, Model } from "@/types/chat";

const MODELS: Model[] = [
  {
    id: "deepseek-chat",
    name: "DeepSeek Chat",
    description: "General-purpose conversational AI",
    contextLength: 32768,
    isAvailable: true,
  },
  {
    id: "deepseek-coder",
    name: "DeepSeek Coder",
    description: "Specialized for coding tasks",
    contextLength: 16384,
    isAvailable: true,
  },
  {
    id: "deepseek-math",
    name: "DeepSeek Math",
    description: "Advanced mathematical reasoning",
    contextLength: 8192,
    isAvailable: true,
  },
];

export const useChat = () => {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [currentConversationId, setCurrentConversationId] = useState<
    string | null
  >(null);
  const [selectedModel, setSelectedModel] = useState<Model>(MODELS[0]);
  const [isLoading, setIsLoading] = useState(false);

  const currentConversation = conversations.find(
    (c) => c.id === currentConversationId
  );

  const createConversation = useCallback(() => {
    const newConversation: Conversation = {
      id: Date.now().toString(),
      title: "New Chat",
      messages: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    setConversations((prev) => [newConversation, ...prev]);
    setCurrentConversationId(newConversation.id);
    return newConversation;
  }, []);

  const deleteConversation = useCallback(
    (id: string) => {
      setConversations((prev) => prev.filter((c) => c.id !== id));
      if (currentConversationId === id) {
        setCurrentConversationId(null);
      }
    },
    [currentConversationId]
  );

  const sendMessage = useCallback(
    async (content: string) => {
      if (!content.trim()) return;

      let conversation = currentConversation;
      if (!conversation) {
        conversation = createConversation();
      }

      const userMessage: Message = {
        id: Date.now().toString(),
        content,
        role: "user",
        timestamp: new Date(),
        model: selectedModel.id,
      };

      // Update conversation with user message
      setConversations((prev) =>
        prev.map((c) =>
          c.id === conversation!.id
            ? {
                ...c,
                messages: [...c.messages, userMessage],
                title:
                  c.messages.length === 0
                    ? content.slice(0, 30) + (content.length > 30 ? "..." : "")
                    : c.title,
                updatedAt: new Date(),
              }
            : c
        )
      );

      setIsLoading(true);

      try {
        // Simulate API call delay
        await new Promise((resolve) =>
          setTimeout(resolve, 1000 + Math.random() * 2000)
        );

        const assistantMessage: Message = {
          id: (Date.now() + 1).toString(),
          content: generateMockResponse(content, selectedModel.id),
          role: "assistant",
          timestamp: new Date(),
          model: selectedModel.id,
        };

        setConversations((prev) =>
          prev.map((c) =>
            c.id === conversation!.id
              ? {
                  ...c,
                  messages: [...c.messages, assistantMessage],
                  updatedAt: new Date(),
                }
              : c
          )
        );
      } catch (error) {
        console.error("Error sending message:", error);
      } finally {
        setIsLoading(false);
      }
    },
    [currentConversation, selectedModel, createConversation]
  );

  const generateMockResponse = (userInput: string, modelId: string): string => {
    const lowerInput = userInput.toLowerCase();

    if (modelId === "deepseek-coder") {
      if (
        lowerInput.includes("code") ||
        lowerInput.includes("function") ||
        lowerInput.includes("javascript") ||
        lowerInput.includes("python")
      ) {
        return `Here's a code example for your request:\n\n\`\`\`javascript\nfunction example() {\n  // This is a mock response from DeepSeek Coder\n  console.log("Hello, world!");\n  return "Generated by ${modelId}";\n}\n\nexample();\n\`\`\`\n\nThis code demonstrates the concept you asked about. Would you like me to explain any part of it or modify it for your specific use case?`;
      }
    }

    if (modelId === "deepseek-math") {
      if (
        lowerInput.includes("math") ||
        lowerInput.includes("calculate") ||
        lowerInput.includes("equation")
      ) {
        return `Let me solve this mathematical problem for you:\n\n**Solution:**\n\nGiven the problem, I'll work through it step by step:\n\n1. First, I'll identify the key variables\n2. Then apply the relevant mathematical principles\n3. Finally, provide the solution with verification\n\n*Note: This is a mock response from DeepSeek Math model.*\n\nWould you like me to explain any part of the solution in more detail?`;
      }
    }

    const responses = [
      `I understand your question about "${userInput}". As an AI assistant powered by ${selectedModel.name}, I'm here to help you with detailed explanations and insights.\n\nLet me break down the key points:\n\n• **Context**: Your query relates to several important concepts\n• **Analysis**: I can provide both theoretical and practical perspectives\n• **Applications**: There are multiple ways to approach this topic\n\nWould you like me to dive deeper into any specific aspect?`,

      `Thank you for your question. Based on my understanding using the ${selectedModel.name} model, I can provide you with a comprehensive response.\n\n## Key Insights\n\nYour question touches on several important areas:\n\n1. **Primary considerations**\n2. **Secondary factors**\n3. **Practical implications**\n\nI'd be happy to elaborate on any of these points or answer follow-up questions you might have.`,

      `Interesting question! Using ${selectedModel.name}, I can offer you a detailed perspective on this topic.\n\n**Analysis:**\n- This is a multifaceted issue\n- There are several approaches to consider\n- The optimal solution depends on your specific context\n\n**Recommendations:**\nBased on current best practices, I'd suggest considering multiple angles and gathering additional context if needed.\n\nWhat specific aspect would you like me to focus on?`,
    ];

    return responses[Math.floor(Math.random() * responses.length)];
  };

  return {
    conversations,
    currentConversation,
    selectedModel,
    isLoading,
    models: MODELS,
    setSelectedModel,
    setCurrentConversationId,
    createConversation,
    deleteConversation,
    sendMessage,
  };
};
